INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'BUDGET','BUDGET','BUDGET','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'PURPOSE','PURPOSE','PURPOSE','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'REQ_POSSESSION_TIME_LINE','REQ_POSSESSION_TIME_LINE','REQ_POSSESSION_TIME_LINE','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'SALUTATION','SALUTATION','SALUTATION','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'OCCUPATION','OCCUPATION','OCCUPATION','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'COUNTRY','COUNTRY','COUNTRY','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'COMMUNICATION_MEDIUM','COMMUNICATION_MEDIUM','COMMUNICATION_MEDIUM','Y');

INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'INDUSTRY','INDUSTRY','INDUSTRY','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'AGE_GROUP','AGE_GROUP','AGE_GROUP','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'TYPOLOGY_AREA','TYPOLOGY_AREA','TYPOLOGY_AREA','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'CURENT_RESIDENCE_TYPE','CURENT_RESIDENCE_TYPE','CURRENT_RESIDENCE_TYPE','Y');
INSERT INTO salesforce.M_REFERENCE(M_REFERENCE_ID,NAME,VALUE,DESCRIPTION,ISACTIVE) values(NEXTVAL('salesforce."m_reference_seq"'),'REQUIREMENT_TYPE','REQUIREMENT_TYPE','REQUIREMENT_TYPE','Y');