INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'>30 L','>30 L','>30 L','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'30 - 40 L','30 - 40 L','30 - 40 L','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'41 - 50 L','41 - 50 L','41 - 50 L','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'51 - 60 L','51 - 60 L','51 - 60 L','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'61 - 70 L','61 - 70 L','61 - 70 L','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'71 - 80 L','71 - 80 L','71 - 80 L','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'81 – 90 L','81 – 90 L','81 – 90 L','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'91 L– 1 Cr','91 L– 1 Cr','91 L– 1 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1 – 1.10 Cr','1 – 1.10 Cr','1 – 1.10 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1.11 – 1.25 Cr','1.11 – 1.25 Cr','1.11 – 1.25 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1.25 - 1.50 Cr','1.25 - 1.50 Cr','1.25 - 1.50 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1.50 - 2 Cr','1.50 - 2 Cr','1.50 - 2 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'2 - 2.5 Cr','2 - 2.5 Cr','2 - 2.5 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'2.5 - 3 Cr','2.5 - 3 Cr','2.5 - 3 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'3 - 3.5 Cr','3 - 3.5 Cr','3 - 3.5 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'3.5 - 4 Cr','3.5 - 4 Cr','3.5 - 4 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'4 - 4.5 Cr','4 - 4.5 Cr','4 - 4.5 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'>5 Cr','>5 Cr','>5 Cr','1','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Service','Service','Service','5','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Business','Business','Business','5','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Proffessional','Proffessional','Proffessional','5','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'VIP','VIP','VIP','5','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Retired','Retired','Retired','5','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'House-wife','House-wife','House-wife','5','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'< 6 months','< 6 months','< 6 months','3','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'6 months to 1 year','6 months to 1 year','6 months to 1 year','3','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1 year to 3 years','1 year to 3 years','1 year to 3 years','3','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'> 3 years','> 3 years','> 3 years','3','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Mr.','Mr.','Mr.','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Ms.','Ms.','Ms.','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Mrs.','Mrs.','Mrs.','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Dr.','Dr.','Dr.','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Prof.','Prof.','Prof.','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Cdr','Cdr','Cdr','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Mr and Mrs.','Mr and Mrs.','Mr and Mrs.','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Ms','Ms','Ms','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'M/s.','M/s.','M/s.','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'HUF','HUF','HUF','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Company','Company','Company','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Col','Col','Col','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Capt','Capt','Capt','4','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Internet','Internet','Internet','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Newspaper','Newspaper','Newspaper','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Hoarding','Hoarding','Hoarding','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Radio','Radio','Radio','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Exhibition','Exhibition','Exhibition','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Word of Mouth','Word of Mouth','Word of Mouth','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'SMS','SMS','SMS','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Referral','Referral','Referral','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Godrej Employee','Godrej Employee','Godrej Employee','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Corporate','Corporate','Corporate','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Existing Customer','Existing Customer','Existing Customer','7','Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Other BTL Activities','Other BTL Activities','Other BTL Activities','7','Y');

INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Banking','Banking','Banking',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Retail','Retail','Retail',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'FMCG','FMCG','FMCG',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Real estate','Real estate','Real estate',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Hospitality','Hospitality','Hospitality',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'IT','IT','IT',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Medical','Medical','Medical',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Telecommunications ','Telecommunications ','Telecommunications ',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Other','Other','Other',8,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'< 30','< 30','< 30',9,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'31-35','31-35','31-35',9,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'36-40','36-40','36-40',9,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'41-45','41-45','41-45',9,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'46-50','46-50','46-50',9,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'> 51','> 51','> 51',9,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'< 1200 sft','< 1200 sft','< 1200 sft',10,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1200 - 1500 sft','1200 - 1500 sft','1200 - 1500 sft',10,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1500 - 2000 sft','1500 - 2000 sft','1500 - 2000 sft',10,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'2000 - 3000 sft','2000 - 3000 sft','2000 - 3000 sft',10,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'> 3000 sft','> 3000 sft','> 3000 sft',10,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1 BHK','1 BHK','1 BHK',11,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'2 BHK','2 BHK','2 BHK',11,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'2.5 BHK','2.5 BHK','2.5 BHK',11,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'3 BHK','3 BHK','3 BHK',11,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'4 BHK','4 BHK','4 BHK',11,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'1 BHK','1 BHK','1 BHK',12,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'2 BHK','2 BHK','2 BHK',12,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'2.5 BHK','2.5 BHK','2.5 BHK',12,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'3 BHK','3 BHK','3 BHK',12,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'4 BHK','4 BHK','4 BHK',12,'Y');

INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Self-Use','Self-Use','Self-Use',2,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Investment','Investment','Investment',2,'Y');
INSERT INTO salesforce.M_REFERENCE_LIST(M_REFERENCE_LIST_ID,NAME,VALUE,DESCRIPTION,M_REFERENCE_ID,ISACTIVE)values(NEXTVAL('salesforce."m_reference_list_seq"'),'Weekend/Second home','Weekend/Second home','Weekend/Second home',2,'Y');

