package com.godrej.properties.dto;

public enum SysConfigEnum {
	HOLD_TIME,
	OFFER_CREATION_TEMPLATE,
	OFFER_CREATION_TEMPLATE_DEFAULT,
	OFFER_CREATION_VALIDATION_SOURCE,
	OFFER_CREATION_VALIDATION_PERC,
	PREPAYMENT_INCLUDE_GST,
	PAYMENT_TRX_ALLOWED_DAYS
	,OFFER_CREATION_CONFIG_AMOUNT,
	DRUPAL_API_ENDPOINT,
}
